name: app2_module
description: "A new Flutter package project."
version: 0.0.2
homepage: https://github.com/Alienjob/flutter_monorepo

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  component1:
    git:
      url: https://github.com/Alienjob/flutter_monorepo.git
      path: repo/components/component1
      ref: 602cc75a24d85697cd3efb20f404b03787b423ba
  component2:
    git:
      url: https://github.com/Alienjob/flutter_monorepo.git
      path: repo/components/component2
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
