name: component1
description: "A new Flutter package project."
version: 0.1.0
homepage: https://github.com/Alienjob/flutter_monorepo

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  module1:
    git:
      url: https://github.com/Alienjob/flutter_monorepo.git
      path: repo/components/module1
      ref: main
  module2:
    git:
      url: https://github.com/Alienjob/flutter_monorepo.git
      path: repo/components/module2
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
